# Generated by Django 5.2.1 on 2025-05-08 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_club', '0002_alter_user_options_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('is_multi_day', models.BooleanField(default=False)),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Проведено'), ('planned', 'Запланировано'), ('in_progress', 'В разработке')], max_length=20)),
                ('difficulty', models.CharField(choices=[('hard', 'Сложный'), ('medium', 'Средний'), ('easy', 'Для новичков')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Администратор'), ('organizer', 'Организатор'), ('participant', 'Участник')], default='participant', max_length=20, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='ClubCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('state', models.CharField(choices=[('in_use', 'Используется'), ('not_in_use', 'Не используется'), ('hidden', 'Спрятана')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('hidden_location', models.CharField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_club.user')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_organizer', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_club.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_club.user')),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(through='travel_club.EventParticipation', to='travel_club.user'),
        ),
        migrations.CreateModel(
            name='RouteTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_club.event')),
            ],
        ),
    ]
