# Generated by Django 5.2.1 on 2025-05-09 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_club', '0003_event_alter_user_user_type_clubcard_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubcard',
            options={'verbose_name': 'Клубная карта', 'verbose_name_plural': 'Клубные карты'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='eventparticipation',
            options={'verbose_name': 'Участник мероприятия', 'verbose_name_plural': 'Участники мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='routetrack',
            options={'verbose_name': 'Трек маршрута', 'verbose_name_plural': 'Треки маршрута'},
        ),
        migrations.AlterField(
            model_name='clubcard',
            name='hidden_location',
            field=models.CharField(blank=True, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='clubcard',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='clubcard',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_club.user', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='clubcard',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='clubcard',
            name='sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата продажи'),
        ),
        migrations.AlterField(
            model_name='clubcard',
            name='state',
            field=models.CharField(choices=[('in_use', 'Используется'), ('not_in_use', 'Не используется'), ('hidden', 'Спрятана')], max_length=20, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='event',
            name='actual_date',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическая дата'),
        ),
        migrations.AlterField(
            model_name='event',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='difficulty',
            field=models.CharField(choices=[('hard', 'Сложный'), ('medium', 'Средний'), ('easy', 'Для новичков')], max_length=20, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=50, verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_multi_day',
            field=models.BooleanField(default=False, verbose_name='Многодневный'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(through='travel_club.EventParticipation', to='travel_club.user', verbose_name='Участники мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='planned_date',
            field=models.DateField(verbose_name='Запланированная дата'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('completed', 'Проведено'), ('planned', 'Запланировано'), ('in_progress', 'В разработке')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_club.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='is_organizer',
            field=models.BooleanField(default=False, verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_club.user', verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='routetrack',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Дистаниця'),
        ),
        migrations.AlterField(
            model_name='routetrack',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_club.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='routetrack',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
