# Generated by Django 5.2.1 on 2025-05-09 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_club', '0004_alter_clubcard_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_club.clubcard', verbose_name='Клубная карта'),
        ),
    ]
